-- 코드를 입력하세요
SELECT COUNT(USER_ID) AS USERS
FROM USER_INFO
WHERE DATE_FORMAT(JOINED, '%Y') LIKE '2021'
AND AGE BETWEEN 20 AND 29;

-- 문자열 잘라서 년도로만 비교하는 함수들이 있다.
-- DATE_FORMAT(JOINED, '%Y') LIKE '2021'
-- LEFT(JOINED, 4) = '2021'

-- MID(JOINED, 1, 4) --(자를문자열, 시작위치, 가져올개수)
-- RIGHT(JOINED, 2) --LEFT의 반대