-- 코드를 작성해주세요
SELECT  ROUTE,
        CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE,
        CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC

-- ORDER BY에서 ALIAS로 설정한 TOTAL_DISTANCE로 정렬을 할때 테스트 실패. 이유는?
-- 해당 컬럼의 값은 concat으로 문자열화되었기 때문에 순서를 정확히 출력할 수 없기 때문.

-- ORDER BY TOTAL_DISTANCE DESC (x)
-- ORDER BY SUM(D_BETWEEN_DIST) DESC (o)