-- 코드를 작성해주세요
SELECT COUNT(ID) AS FISH_COUNT, FISH_NAME
FROM FISH_INFO A
INNER JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY FISH_NAME
ORDER BY FISH_COUNT DESC

-- JOIN USING(FISH_NAME) 해도 ok.