-- 코드를 입력하세요
-- 서브쿼리
-- SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
-- FROM USED_GOODS_BOARD
-- WHERE STATUS = 'DONE'
-- GROUP BY WRITER_ID
-- HAVING 700000 <= TOTAL_SALES;

SELECT WRITER_ID, NICKNAME, TOTAL_SALES
FROM USED_GOODS_USER a
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING 700000 <= TOTAL_SALES) b
ON a.USER_ID = b.WRITER_ID
ORDER BY TOTAL_SALES;