-- WHERE절 서브쿼리 이용하기
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO A
WHERE ITEM_ID IN (
    SELECT C.ITEM_ID
    FROM ITEM_INFO B, ITEM_TREE C
    WHERE RARITY = 'RARE'
    AND B.ITEM_ID = C.PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC