-- 2022년 8월부터 10월까지 각 자동차의 전체 대여 횟수를 계산
WITH CAR_TOTAL_COUNT AS (
    SELECT CAR_ID, COUNT(*)
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022
      AND MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5 -- 전체 기간 동안 5회 이상 대여된 자동차만 필터링
)

-- 최종 결과: 월별 자동차별 대여 횟수 출력
SELECT MONTH(START_DATE) MONTH, C.CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
JOIN CAR_TOTAL_COUNT T ON C.CAR_ID = T.CAR_ID
WHERE YEAR(START_DATE) = 2022
  AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY C.CAR_ID, MONTH(START_DATE)
ORDER BY MONTH ASC, C.CAR_ID DESC;