-- 코드를 작성해주세요
SELECT  YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA
ORDER BY YEAR, YEAR_DEV

-- PARTIION BY 윈도우함수 중 하나로 윈도우함수는 GROUP BY와 유사하지만 집계가 없어 행이 합쳐지지 않는다.