-- 코드를 입력하세요
SELECT FLAVOR
FROM FIRST_HALF
NATURAL JOIN ICECREAM_INFO
WHERE INGREDIENT_TYPE = 'fruit_based'
AND TOTAL_ORDER >= 3000
ORDER BY TOTAL_ORDER DESC;

-- 테이블간의 동일한 컬럼이 2개 이상일 경우 USING조인을 사용할 수 있다.
-- JOIN ICECREAM_INFO USING(FLAVOR)
