-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, A.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_GRADE A
LEFT JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO
WHERE YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1